name: UI autotests

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run test project
        run: pytest -v tests/test_courses_page.py
